DROP TABLE JUEGO;
DROP TABLE CASINO;
DROP TABLE USUARIO;
DROP TABLE NUMERO;
DROP TABLE GALGO;

DROP SEQUENCE SEQ_CASINO;
DROP SEQUENCE SEQ_JUEGO;

CREATE TABLE CASINO (
    ID_CASINO NUMBER,
    NOMBRE VARCHAR2(100),
    CONSTRAINT PK_CASINO PRIMARY KEY (ID_CASINO)
);

CREATE TABLE JUEGO (
    ID_JUEGO NUMBER,
    NOMBRE VARCHAR2(100),
    FOTO VARCHAR2(200),
    URL VARCHAR2(200),
    ID_CASINO NUMBER,
    CONSTRAINT PK_JUEGO PRIMARY KEY (ID_JUEGO),
    CONSTRAINT FK_CASINO FOREIGN KEY (ID_CASINO) REFERENCES CASINO(ID_CASINO)
);

CREATE TABLE USUARIO (
    ID_USUARIO VARCHAR2(100),
    PASSWD VARCHAR2(100),
    NOMBRE VARCHAR2(100),
    APELLIDOS VARCHAR2(100),
    DNI VARCHAR2(20),
    SALDO NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE NUMERO (
    ID_NUMERO NUMBER,
    VECES NUMBER,
    CONSTRAINT PK_NUMERO PRIMARY KEY (ID_NUMERO)
);

CREATE TABLE GALGO (
    DORSAL NUMBER,
    NOMBRE VARCHAR2(100),
    RITMO NUMBER,
    EXPERIENCIA NUMBER,
    CUOTA NUMBER,
    CANTIDAD_APOSTADA NUMBER,
    DISTANCIA NUMBER,
    TERMINO_CARRERA VARCHAR2(100),
    GANANCIA NUMBER,
    CONSTRAINT PK_GALGO PRIMARY KEY (DORSAL)
);

CREATE SEQUENCE SEQ_CASINO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE SEQ_JUEGO
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999999999999999999
    MINVALUE 1
    NOCACHE
    NOCYCLE;

INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Golfo', 1, 96, 92, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Ron', 11, 90, 93, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Richard', 16, 93, 91, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Widmark', 55, 92, 89, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Brenda', 63, 91, 88, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Jack', 44, 90, 97, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Zaca', 14, 94, 98, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Nala', 18, 86, 80, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Simba', 31, 83, 85, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Beethoven', 10, 82, 84, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Bruno', 4, 88, 89, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Pancho', 81, 76, 75, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Patán', 77, 82, 89, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Pluto', 24, 79, 79, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Laika', 20, 81, 84, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Einstein', 27, 83, 85, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Max', 22, 78, 79, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Duna', 21, 70, 71, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Zeus', 23, 81, 87, 0, 0, 0, '', 0);
INSERT INTO GALGO (NOMBRE, DORSAL, RITMO, EXPERIENCIA, CUOTA, CANTIDAD_APOSTADA, DISTANCIA, TERMINO_CARRERA, GANANCIA) VALUES ('Coco', 2, 65, 66, 0, 0, 0, '', 0);

INSERT INTO Numero (id_numero, veces) VALUES (0, 0);
INSERT INTO Numero (id_numero, veces) VALUES (1, 0);
INSERT INTO Numero (id_numero, veces) VALUES (2, 0);
INSERT INTO Numero (id_numero, veces) VALUES (3, 0);
INSERT INTO Numero (id_numero, veces) VALUES (4, 0);
INSERT INTO Numero (id_numero, veces) VALUES (5, 0);
INSERT INTO Numero (id_numero, veces) VALUES (6, 0);
INSERT INTO Numero (id_numero, veces) VALUES (7, 0);
INSERT INTO Numero (id_numero, veces) VALUES (8, 0);
INSERT INTO Numero (id_numero, veces) VALUES (9, 0);
INSERT INTO Numero (id_numero, veces) VALUES (10, 0);
INSERT INTO Numero (id_numero, veces) VALUES (11, 0);
INSERT INTO Numero (id_numero, veces) VALUES (12, 0);
INSERT INTO Numero (id_numero, veces) VALUES (13, 0);
INSERT INTO Numero (id_numero, veces) VALUES (14, 0);
INSERT INTO Numero (id_numero, veces) VALUES (15, 0);
INSERT INTO Numero (id_numero, veces) VALUES (16, 0);
INSERT INTO Numero (id_numero, veces) VALUES (17, 0);
INSERT INTO Numero (id_numero, veces) VALUES (18, 0);
INSERT INTO Numero (id_numero, veces) VALUES (19, 0);
INSERT INTO Numero (id_numero, veces) VALUES (20, 0);
INSERT INTO Numero (id_numero, veces) VALUES (21, 0);
INSERT INTO Numero (id_numero, veces) VALUES (22, 0);
INSERT INTO Numero (id_numero, veces) VALUES (23, 0);
INSERT INTO Numero (id_numero, veces) VALUES (24, 0);
INSERT INTO Numero (id_numero, veces) VALUES (25, 0);
INSERT INTO Numero (id_numero, veces) VALUES (26, 0);
INSERT INTO Numero (id_numero, veces) VALUES (27, 0);
INSERT INTO Numero (id_numero, veces) VALUES (28, 0);
INSERT INTO Numero (id_numero, veces) VALUES (29, 0);
INSERT INTO Numero (id_numero, veces) VALUES (30, 0);
INSERT INTO Numero (id_numero, veces) VALUES (31, 0);
INSERT INTO Numero (id_numero, veces) VALUES (32, 0);
INSERT INTO Numero (id_numero, veces) VALUES (33, 0);
INSERT INTO Numero (id_numero, veces) VALUES (34, 0);
INSERT INTO Numero (id_numero, veces) VALUES (35, 0);
INSERT INTO Numero (id_numero, veces) VALUES (36, 0);

